name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Puoi anche cambiare questa parte per usare un runner diverso

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup ChromeDriver
        uses: browser-actions/setup-chrome@v1

      - name: Run Behave tests
        run: |
          behave --format=pretty

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: behave-test-report
          path: reports/report.json
