name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install behave-html-formatter  # Installa il plugin per il report HTML

      - name: Setup ChromeDriver
        uses: browser-actions/setup-chrome@v1

      - name: Run Behave tests
        run: |
        # -- FILE: behave.ini
        # Define ALIAS for HtmlFormatter.
          [ behave.formatters ]
          html = behave_html_formatter:HTMLFormatter
          behave --format=html --outfile=reports/report.html  # Esegui i test con il formato HTML

      - name: Upload test results (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: behave-test-report
          path: reports/report.html

      - name: Set up GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports

